#!/bin/env zsh
set -xe

projDir=${0:a:h}
projName=${projDir:t}
targetDir="${SYPLUGINDIR:h:h}/conf/appearance/themes/${projName}"
rm -rf ${targetDir}
mkdir -p ${targetDir}
rsync -ru --exclude={'.git','.github'} "$projDir/" "$targetDir/"


